-- Add new stats tables

SET ESCAPE ON
DEFINE v_app_root = "D:\\DEMO\\ORACLE-APPSDEMO-MAIN"
@'&v_app_root\\config\\set_env'


CONNECT &v_app_owner/&v_pwd@&v_dbconnect

DROP TABLE STATS_PROJECT CASCADE CONSTRAINTS;

CREATE TABLE STATS_PROJECT (
  STATS_PROJECT_ID  NUMBER(28,0) GENERATED ALWAYS AS IDENTITY,  
  DESCRIPTION       VARCHAR2(100)

);
   
CREATE UNIQUE INDEX STATS_PROJECT_IDX ON STATS_PROJECT (STATS_PROJECT_ID);
ALTER TABLE STATS_PROJECT ADD CONSTRAINT STATS_PROJECT_PK PRIMARY KEY (STATS_PROJECT_ID) ENABLE;

DROP TABLE STATS_DATA CASCADE CONSTRAINTS;

CREATE TABLE STATS_DATA (
  STATS_DATA_ID     NUMBER(28,0) GENERATED ALWAYS AS IDENTITY, 
  STATS_PROJECT_ID  NUMBER(28,0),
  DESCRIPTION       VARCHAR2(100),
  STATS_VALUE       NUMBER(38)
);
    
CREATE UNIQUE INDEX STATS_DATA_IDX ON STATS_DATA (STATS_DATA_ID);
ALTER TABLE STATS_DATA ADD CONSTRAINT STATS_DATA_PK PRIMARY KEY (STATS_DATA_ID) ENABLE;
ALTER TABLE STATS_DATA ADD CONSTRAINT STATS_DATA_STATS_PROJECT_FK FOREIGN KEY (STATS_PROJECT_ID) REFERENCES STATS_PROJECT (STATS_PROJECT_ID) ENABLE;


GRANT DELETE, INSERT, SELECT, UPDATE ON STATS_PROJECT           TO &v_connect_user;
GRANT DELETE, INSERT, SELECT, UPDATE ON STATS_DATA              TO &v_connect_user;


CONNECT &v_connect_user/&v_connect_pwd@&v_dbconnect
  
CREATE OR REPLACE SYNONYM STATS_PROJECT         FOR &v_app_owner\.STATS_PROJECT;
CREATE OR REPLACE SYNONYM STATS_DATA            FOR &v_app_owner\.STATS_DATA;